# ═══════════════════════════════════════════════════════════════
# Path Tracker - Cloud Build Configuration
# ═══════════════════════════════════════════════════════════════
# Triggered on push to main branch
# Builds Docker image and deploys to Cloud Run
# ═══════════════════════════════════════════════════════════════

substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: pathtracker
  _REPOSITORY: pathtracker
  _CLOUD_SQL_INSTANCE: path-tracker-484312:europe-west1:pathtracker-db

steps:
  # ─────────────────────────────────────
  # Step 1: Build Docker image
  # ─────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build'

  # ─────────────────────────────────────
  # Step 2: Push Docker image to Artifact Registry
  # ─────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}'
    id: 'push'
    waitFor: ['build']

  # ─────────────────────────────────────
  # Step 3: Deploy to Cloud Run
  # ─────────────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--vpc-connector'
      - 'pathtracker-connector'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,CLERK_SECRET_KEY=CLERK_SECRET_KEY:latest,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:latest,CLERK_WEBHOOK_SECRET=CLERK_WEBHOOK_SECRET:latest,ADMIN_ACCOUNTS=ADMIN_ACCOUNTS:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_APP_URL=https://tracker.pathwave.io'
    id: 'deploy'
    waitFor: ['push']

# ─────────────────────────────────────
# Build options
# ─────────────────────────────────────
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Timeout for the entire build
timeout: '1200s'
